"""init_tables

Revision ID: 68955653ba40
Revises: 
Create Date: 2026-05-28 11:12:30.725683
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68955653ba40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_currency_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('from_currency', sa.String(length=10), nullable=False, comment='源币种'),
    sa.Column('to_currency', sa.String(length=10), nullable=False, comment='目标币种'),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False, comment='汇率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_dim_currency_rate_date_pair', 'dim_currency_rate', ['date', 'from_currency', 'to_currency'], unique=True)
    op.create_table('dim_listing',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Listing ID(领星)'),
    sa.Column('asin', sa.String(length=20), nullable=False, comment='ASIN'),
    sa.Column('sku', sa.String(length=200), nullable=True, comment='SKU'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='所属店铺ID'),
    sa.Column('buy_box_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Buy Box 价格'),
    sa.Column('buy_box_owner', sa.String(length=200), nullable=True, comment='Buy Box 卖家'),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True, comment='评分'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='评论数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态: 1-在售 0-停售'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index('ix_dim_listing_asin', 'dim_listing', ['asin'], unique=False)
    op.create_index('ix_dim_listing_sid', 'dim_listing', ['sid'], unique=False)
    op.create_index('ix_dim_listing_sid_asin', 'dim_listing', ['sid', 'asin'], unique=False)
    op.create_table('dim_marketplace',
    sa.Column('marketplace_id', sa.Integer(), nullable=False, comment='市场ID'),
    sa.Column('marketplace_name', sa.String(length=100), nullable=False, comment='市场名称'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='币种代码'),
    sa.Column('region', sa.String(length=50), nullable=False, comment='所属区域'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('marketplace_id')
    )
    op.create_index('ix_dim_marketplace_region', 'dim_marketplace', ['region'], unique=False)
    op.create_table('dim_shop',
    sa.Column('sid', sa.Integer(), nullable=False, comment='店铺ID(领星)'),
    sa.Column('shop_name', sa.String(length=200), nullable=False, comment='店铺名称'),
    sa.Column('marketplace_id', sa.Integer(), nullable=False, comment='市场ID'),
    sa.Column('seller_id', sa.String(length=64), nullable=True, comment='亚马逊卖家ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态: 1-启用 0-停用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index('ix_dim_shop_marketplace', 'dim_shop', ['marketplace_id'], unique=False)
    op.create_index('ix_dim_shop_status', 'dim_shop', ['status'], unique=False)
    op.create_table('dim_sku',
    sa.Column('sku_id', sa.Integer(), nullable=False, comment='SKU ID(领星)'),
    sa.Column('msku', sa.String(length=200), nullable=True, comment='卖家SKU'),
    sa.Column('asin', sa.String(length=20), nullable=True, comment='ASIN'),
    sa.Column('product_name', sa.String(length=500), nullable=True, comment='商品名称'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='所属店铺ID'),
    sa.Column('category', sa.String(length=200), nullable=True, comment='分类'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态: 1-启用 0-停用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index('ix_dim_sku_asin', 'dim_sku', ['asin'], unique=False)
    op.create_index('ix_dim_sku_sid', 'dim_sku', ['sid'], unique=False)
    op.create_index('ix_dim_sku_sid_asin', 'dim_sku', ['sid', 'asin'], unique=False)
    op.create_table('dws_sales_daily',
    sa.Column('date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='店铺ID'),
    sa.Column('marketplace_id', sa.Integer(), nullable=False, comment='市场ID'),
    sa.Column('gmv', sa.Numeric(precision=14, scale=2), nullable=False, comment='GMV 总额'),
    sa.Column('order_count', sa.Integer(), nullable=False, comment='订单数'),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='退款总额'),
    sa.Column('net_sales', sa.Numeric(precision=14, scale=2), nullable=False, comment='净销售额'),
    sa.Column('item_count', sa.Integer(), nullable=False, comment='商品件数'),
    sa.Column('avg_order_value', sa.Numeric(precision=14, scale=2), nullable=True, comment='客单价'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('date', 'sid', 'marketplace_id')
    )
    op.create_index('ix_dws_sales_sid', 'dws_sales_daily', ['sid'], unique=False)
    op.create_table('ods_ad_sp_campaign',
    sa.Column('report_date', sa.Date(), nullable=False, comment='报表日期'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='店铺ID'),
    sa.Column('campaign_id', sa.String(length=64), nullable=False, comment='广告活动ID'),
    sa.Column('campaign_name', sa.String(length=300), nullable=True, comment='广告活动名称'),
    sa.Column('ad_group_name', sa.String(length=300), nullable=True, comment='广告组名称(可选)'),
    sa.Column('impressions', sa.Integer(), nullable=False, comment='曝光量'),
    sa.Column('clicks', sa.Integer(), nullable=False, comment='点击量'),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False, comment='花费'),
    sa.Column('orders', sa.Integer(), nullable=False, comment='广告订单数'),
    sa.Column('sales', sa.Numeric(precision=14, scale=2), nullable=False, comment='广告销售额'),
    sa.Column('acos', sa.Numeric(precision=8, scale=4), nullable=True, comment='ACOS'),
    sa.Column('cpc', sa.Numeric(precision=12, scale=4), nullable=True, comment='单次点击成本'),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True, comment='点击率'),
    sa.Column('cvr', sa.Numeric(precision=8, scale=4), nullable=True, comment='转化率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('report_date', 'sid', 'campaign_id')
    )
    op.create_index('ix_ods_ad_sp_camp_date', 'ods_ad_sp_campaign', ['report_date'], unique=False)
    op.create_index('ix_ods_ad_sp_camp_sid', 'ods_ad_sp_campaign', ['sid'], unique=False)
    op.create_table('ods_ad_sp_group',
    sa.Column('report_date', sa.Date(), nullable=False, comment='报表日期'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='店铺ID'),
    sa.Column('ad_group_id', sa.String(length=64), nullable=False, comment='广告组ID'),
    sa.Column('campaign_id', sa.String(length=64), nullable=True, comment='所属广告活动ID'),
    sa.Column('ad_group_name', sa.String(length=300), nullable=True, comment='广告组名称'),
    sa.Column('impressions', sa.Integer(), nullable=False, comment='曝光量'),
    sa.Column('clicks', sa.Integer(), nullable=False, comment='点击量'),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False, comment='花费'),
    sa.Column('orders', sa.Integer(), nullable=False, comment='广告订单数'),
    sa.Column('sales', sa.Numeric(precision=14, scale=2), nullable=False, comment='广告销售额'),
    sa.Column('acos', sa.Numeric(precision=8, scale=4), nullable=True, comment='ACOS'),
    sa.Column('cpc', sa.Numeric(precision=12, scale=4), nullable=True, comment='单次点击成本'),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True, comment='点击率'),
    sa.Column('cvr', sa.Numeric(precision=8, scale=4), nullable=True, comment='转化率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('report_date', 'sid', 'ad_group_id')
    )
    op.create_index('ix_ods_ad_sp_grp_campaign', 'ods_ad_sp_group', ['campaign_id'], unique=False)
    op.create_index('ix_ods_ad_sp_grp_date', 'ods_ad_sp_group', ['report_date'], unique=False)
    op.create_index('ix_ods_ad_sp_grp_sid', 'ods_ad_sp_group', ['sid'], unique=False)
    op.create_table('ods_amazon_order',
    sa.Column('amazon_order_id', sa.String(length=32), nullable=False, comment='亚马逊订单号'),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True, comment='下单时间'),
    sa.Column('last_update_date', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.Column('order_status', sa.String(length=30), nullable=True, comment='订单状态'),
    sa.Column('order_total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='订单总金额'),
    sa.Column('order_total_currency', sa.String(length=10), nullable=True, comment='订单金额币种'),
    sa.Column('marketplace_id', sa.Integer(), nullable=True, comment='市场ID'),
    sa.Column('sid', sa.Integer(), nullable=True, comment='店铺ID'),
    sa.Column('fulfillment_channel', sa.String(length=30), nullable=True, comment='配送渠道: AFN/MFN'),
    sa.Column('shipment_service_level', sa.String(length=50), nullable=True, comment='配送服务级别'),
    sa.Column('number_of_items_shipped', sa.Integer(), nullable=True, comment='已发货商品数'),
    sa.Column('number_of_items_unshipped', sa.Integer(), nullable=True, comment='未发货商品数'),
    sa.Column('payment_method', sa.String(length=30), nullable=True, comment='支付方式'),
    sa.Column('is_business_order', sa.Boolean(), nullable=True, comment='是否企业订单'),
    sa.Column('is_premium_order', sa.Boolean(), nullable=True, comment='是否加急订单'),
    sa.Column('buyer_email', sa.String(length=200), nullable=True, comment='买家邮箱(脱敏)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('amazon_order_id')
    )
    op.create_index('ix_ods_order_purchase_date', 'ods_amazon_order', ['purchase_date'], unique=False)
    op.create_index('ix_ods_order_sid', 'ods_amazon_order', ['sid'], unique=False)
    op.create_index('ix_ods_order_sid_purchase', 'ods_amazon_order', ['sid', 'purchase_date'], unique=False)
    op.create_index('ix_ods_order_status', 'ods_amazon_order', ['order_status'], unique=False)
    op.create_table('ods_fba_inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='快照日期'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='店铺ID'),
    sa.Column('sku', sa.String(length=200), nullable=True, comment='卖家SKU'),
    sa.Column('asin', sa.String(length=20), nullable=True, comment='ASIN'),
    sa.Column('fnsku', sa.String(length=20), nullable=True, comment='FNSKU'),
    sa.Column('marketplace_id', sa.Integer(), nullable=True, comment='市场ID'),
    sa.Column('fulfillment_type', sa.String(length=20), nullable=True, comment='库存类型'),
    sa.Column('quantity_available', sa.Integer(), nullable=True, comment='可用数量'),
    sa.Column('quantity_reserved', sa.Integer(), nullable=True, comment='预留数量'),
    sa.Column('quantity_unsellable', sa.Integer(), nullable=True, comment='不可售数量'),
    sa.Column('quantity_inbound', sa.Integer(), nullable=True, comment='在途数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'sid', 'sku', 'marketplace_id', name='uq_ods_fba_inv_snapshot_sku')
    )
    op.create_index('ix_ods_fba_inv_asin', 'ods_fba_inventory', ['asin'], unique=False)
    op.create_index('ix_ods_fba_inv_date', 'ods_fba_inventory', ['snapshot_date'], unique=False)
    op.create_index('ix_ods_fba_inv_sid', 'ods_fba_inventory', ['sid'], unique=False)
    op.create_table('ods_local_inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='快照日期'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='店铺ID'),
    sa.Column('sku', sa.String(length=200), nullable=True, comment='卖家SKU'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('quantity_available', sa.Integer(), nullable=True, comment='可用数量'),
    sa.Column('quantity_inbound', sa.Integer(), nullable=True, comment='在途数量'),
    sa.Column('quantity_pending', sa.Integer(), nullable=True, comment='待处理数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'sid', 'sku', 'warehouse_id', name='uq_ods_local_inv_snapshot_sku_wh')
    )
    op.create_index('ix_ods_local_inv_date', 'ods_local_inventory', ['snapshot_date'], unique=False)
    op.create_index('ix_ods_local_inv_sid', 'ods_local_inventory', ['sid'], unique=False)
    op.create_table('ods_return_order',
    sa.Column('return_order_id', sa.String(length=64), nullable=False, comment='退货单ID'),
    sa.Column('amazon_order_id', sa.String(length=32), nullable=True, comment='关联亚马逊订单号'),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True, comment='退货时间'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='退货原因'),
    sa.Column('sid', sa.Integer(), nullable=True, comment='店铺ID'),
    sa.Column('asin', sa.String(length=20), nullable=True, comment='ASIN'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='退货数量'),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='退款金额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.PrimaryKeyConstraint('return_order_id')
    )
    op.create_index('ix_ods_return_date', 'ods_return_order', ['return_date'], unique=False)
    op.create_index('ix_ods_return_order_id', 'ods_return_order', ['amazon_order_id'], unique=False)
    op.create_index('ix_ods_return_sid', 'ods_return_order', ['sid'], unique=False)
    op.create_table('sync_cursor',
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='目标表名'),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True, comment='上次同步时间'),
    sa.Column('last_sync_id', sa.String(length=128), nullable=True, comment='上次同步位置标记'),
    sa.Column('sync_status', sa.String(length=20), nullable=False, comment='同步状态: idle/running/success/failed'),
    sa.Column('record_count', sa.Integer(), nullable=False, comment='本次同步记录数'),
    sa.Column('error_message', sa.String(length=1000), nullable=True, comment='错误信息'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('ods_amazon_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amazon_order_id', sa.String(length=32), nullable=False, comment='亚马逊订单号'),
    sa.Column('asin', sa.String(length=20), nullable=True, comment='ASIN'),
    sa.Column('sku', sa.String(length=200), nullable=True, comment='卖家SKU'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='商品标题'),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True, comment='订购数量'),
    sa.Column('quantity_shipped', sa.Integer(), nullable=True, comment='发货数量'),
    sa.Column('item_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='商品价格'),
    sa.Column('item_tax', sa.Numeric(precision=12, scale=2), nullable=True, comment='商品税费'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('sync_time', sa.DateTime(timezone=True), nullable=True, comment='同步时间'),
    sa.ForeignKeyConstraint(['amazon_order_id'], ['ods_amazon_order.amazon_order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ods_item_asin', 'ods_amazon_order_item', ['asin'], unique=False)
    op.create_index('ix_ods_item_order_id', 'ods_amazon_order_item', ['amazon_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ods_item_order_id', table_name='ods_amazon_order_item')
    op.drop_index('ix_ods_item_asin', table_name='ods_amazon_order_item')
    op.drop_table('ods_amazon_order_item')
    op.drop_table('sync_cursor')
    op.drop_index('ix_ods_return_sid', table_name='ods_return_order')
    op.drop_index('ix_ods_return_order_id', table_name='ods_return_order')
    op.drop_index('ix_ods_return_date', table_name='ods_return_order')
    op.drop_table('ods_return_order')
    op.drop_index('ix_ods_local_inv_sid', table_name='ods_local_inventory')
    op.drop_index('ix_ods_local_inv_date', table_name='ods_local_inventory')
    op.drop_table('ods_local_inventory')
    op.drop_index('ix_ods_fba_inv_sid', table_name='ods_fba_inventory')
    op.drop_index('ix_ods_fba_inv_date', table_name='ods_fba_inventory')
    op.drop_index('ix_ods_fba_inv_asin', table_name='ods_fba_inventory')
    op.drop_table('ods_fba_inventory')
    op.drop_index('ix_ods_order_status', table_name='ods_amazon_order')
    op.drop_index('ix_ods_order_sid_purchase', table_name='ods_amazon_order')
    op.drop_index('ix_ods_order_sid', table_name='ods_amazon_order')
    op.drop_index('ix_ods_order_purchase_date', table_name='ods_amazon_order')
    op.drop_table('ods_amazon_order')
    op.drop_index('ix_ods_ad_sp_grp_sid', table_name='ods_ad_sp_group')
    op.drop_index('ix_ods_ad_sp_grp_date', table_name='ods_ad_sp_group')
    op.drop_index('ix_ods_ad_sp_grp_campaign', table_name='ods_ad_sp_group')
    op.drop_table('ods_ad_sp_group')
    op.drop_index('ix_ods_ad_sp_camp_sid', table_name='ods_ad_sp_campaign')
    op.drop_index('ix_ods_ad_sp_camp_date', table_name='ods_ad_sp_campaign')
    op.drop_table('ods_ad_sp_campaign')
    op.drop_index('ix_dws_sales_sid', table_name='dws_sales_daily')
    op.drop_table('dws_sales_daily')
    op.drop_index('ix_dim_sku_sid_asin', table_name='dim_sku')
    op.drop_index('ix_dim_sku_sid', table_name='dim_sku')
    op.drop_index('ix_dim_sku_asin', table_name='dim_sku')
    op.drop_table('dim_sku')
    op.drop_index('ix_dim_shop_status', table_name='dim_shop')
    op.drop_index('ix_dim_shop_marketplace', table_name='dim_shop')
    op.drop_table('dim_shop')
    op.drop_index('ix_dim_marketplace_region', table_name='dim_marketplace')
    op.drop_table('dim_marketplace')
    op.drop_index('ix_dim_listing_sid_asin', table_name='dim_listing')
    op.drop_index('ix_dim_listing_sid', table_name='dim_listing')
    op.drop_index('ix_dim_listing_asin', table_name='dim_listing')
    op.drop_table('dim_listing')
    op.drop_index('uq_dim_currency_rate_date_pair', table_name='dim_currency_rate')
    op.drop_table('dim_currency_rate')
    # ### end Alembic commands ###
